#----------------------------------------
# GENERAL SETTINGS
#----------------------------------------

# Site title, appears in the browser tab
title: "Blog JCF"

# Site description in search engine
description: "Blog de difusión de conocimiento JCF."

# Language settings for html and seo
lang: "es_Es"
iso-lang: "es"

# Production url.
url: "https://ct-arenas.github.io"

# Part after .com, etc. Use / if none
baseurl: /


#----------------------------------------
# CONTENT VARIABLES
#----------------------------------------

# Posts, drafts and other collections in '_content' directory
collections_dir: content

# Collections
collections:
  img:
    output: true
    permaling: /:collection/:name

# Index
index_header: "Blogging with Jekyll"
index_description: "En este blog, encontrarás artículos y guías prácticas que abordan desde la importancia de los bancos de semillas comunitarios hasta el impacto positivo de las ferias agroecológicas en México."


# Footer
# Available icons: link, youtube, twitter, facebook, linkedin, instagram
footer_description: Queremos ser un recurso para todos aquellos interesados en aprender, compartir y poner en práctica los principios de la agroecología. Además de ello incluimos nuestras experiencias durante el programa Jóvenes Construyendo el Futuro.
footer_socials:
  -
    link: "/"
    icon: "facebook"
  -
    link: "/"
    icon: "twitter"
  -
    link: "/"
    icon: "instagram"
  -
    link: "/"
    icon: "linkedin"

#----------------------------------------
# JEKYLL SETTINGS
#----------------------------------------

# Default variables for pages. Are in use if not overwritten
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "ct-arenas"
      img: "https://placekitten.com/1300/600"
      tag: Post

# Takes files from root folder, generates site into ./_site
source: .
destination: ./_site

paginate: 4
paginate_path: "page/:num/"

# Excluding dev gem builds from website
exclude: [vendor]

# Jekyll plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-feed
